# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: booking.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'booking.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rbooking.proto\"\x14\n\x06UserID\x12\n\n\x02id\x18\x01 \x01(\t\"\x1a\n\nDateString\x12\x0c\n\x04\x64\x61te\x18\x01 \x01(\t\">\n\x0bUserBooking\x12\x0e\n\x06userid\x18\x01 \x01(\t\x12\x1f\n\x08schedule\x18\x02 \x03(\x0b\x32\r.DateSchedule\",\n\x0c\x44\x61teSchedule\x12\x0c\n\x04\x64\x61te\x18\x01 \x01(\t\x12\x0e\n\x06movies\x18\x02 \x03(\t\"\x07\n\x05\x45mpty2\xc6\x01\n\x07\x42ooking\x12\'\n\x0bGetBookings\x12\x06.Empty\x1a\x0c.UserBooking\"\x00\x30\x01\x12-\n\x12GetBookingByUserID\x12\x07.UserID\x1a\x0c.UserBooking\"\x00\x12\x30\n\x10\x41\x64\x64\x42ookingToUser\x12\x0c.UserBooking\x1a\x0c.UserBooking\"\x00\x12\x31\n\x11GetScheduleByDate\x12\x0b.DateString\x1a\r.DateSchedule\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'booking_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_USERID']._serialized_start=17
  _globals['_USERID']._serialized_end=37
  _globals['_DATESTRING']._serialized_start=39
  _globals['_DATESTRING']._serialized_end=65
  _globals['_USERBOOKING']._serialized_start=67
  _globals['_USERBOOKING']._serialized_end=129
  _globals['_DATESCHEDULE']._serialized_start=131
  _globals['_DATESCHEDULE']._serialized_end=175
  _globals['_EMPTY']._serialized_start=177
  _globals['_EMPTY']._serialized_end=184
  _globals['_BOOKING']._serialized_start=187
  _globals['_BOOKING']._serialized_end=385
# @@protoc_insertion_point(module_scope)
